// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDK9iHguaOxhQaJznosa3kmlgSnfiwFS5g',
//     appId: '1:183676376870:web:2f55f5fc6a557a8df493e7',
//     messagingSenderId: '183676376870',
//     projectId: 'shipmate-firebase-account',
//     authDomain: 'shipmate-firebase-account.firebaseapp.com',
//     storageBucket: 'shipmate-firebase-account.firebasestorage.app',
//     measurementId: 'G-MM7CXHYY3C',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCq2HO4D6Nb3MeomjWhbqr4aRjD8gOZ77U',
//     appId: '1:183676376870:android:518dd3a7adfc0404f493e7',
//     messagingSenderId: '183676376870',
//     projectId: 'shipmate-firebase-account',
//     storageBucket: 'shipmate-firebase-account.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAPuoNNzQ-JcDlDiEUpyTmxbv90pXrXV6I',
//     appId: '1:183676376870:ios:4fdf36b255a99051f493e7',
//     messagingSenderId: '183676376870',
//     projectId: 'shipmate-firebase-account',
//     storageBucket: 'shipmate-firebase-account.firebasestorage.app',
//     iosBundleId: 'com.example.shipmateFlutterApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAPuoNNzQ-JcDlDiEUpyTmxbv90pXrXV6I',
//     appId: '1:183676376870:ios:4fdf36b255a99051f493e7',
//     messagingSenderId: '183676376870',
//     projectId: 'shipmate-firebase-account',
//     storageBucket: 'shipmate-firebase-account.firebasestorage.app',
//     iosBundleId: 'com.example.shipmateFlutterApp',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDK9iHguaOxhQaJznosa3kmlgSnfiwFS5g',
//     appId: '1:183676376870:web:4dd4d9e17435a901f493e7',
//     messagingSenderId: '183676376870',
//     projectId: 'shipmate-firebase-account',
//     authDomain: 'shipmate-firebase-account.firebaseapp.com',
//     storageBucket: 'shipmate-firebase-account.firebasestorage.app',
//     measurementId: 'G-39N9PFZHV1',
//   );
// }
